services:
  product-web:
    image: nginx:alpine
    ports:
      - 8080:80
    volumes:
      - ./product-svc/:/var/www
      - ./product-svc/.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - product-app
    networks:
      - product-network

  product-app:
    image: php:8.3-fpm
    volumes:
      - ./product-svc:/var/www
    ports:
      - 9001:9000
    depends_on:
      - product-db
    networks:
      - product-network

  product-db:
    image: mariadb
    restart: always
    ports:
      - 3317:3306
    volumes:
      - ./product-svc/var/db:/var/lib/mysql:rw
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    networks:
      - product-network

networks:
  product-network:
    driver: bridge