@product_api_url=http://product.svc.local
@product_port=8081

@orders_api_url=http://orders.svc.local
@orders_port=8082

### --------- Product service API -----------------------

### List products
GET {{product_api_url}}:{{product_port}}/products

### Create product
POST {{product_api_url}}:{{product_port}}/products
content-type: application/json

{
    "name": "Test product #1",
    "price": 3.99,
    "qty": 10
}

### Get single product (without income)
@product_id=0193ea09-6191-7c09-a4b5-fa788d7a47c3
GET {{product_api_url}}:{{product_port}}/products/{{product_id}}

### Change product Inventory
PUT {{product_api_url}}:{{product_port}}/products/{{product_id}}
content-type: application/json

{
    "qty": 20
}

### -------------- Orders service API ------------------------

### List orders
GET {{orders_api_url}}:{{orders_port}}/orders

### Make Order
POST {{orders_api_url}}:{{orders_port}}/orders
content-type: application/json

{
    "product": "0193ea09-6191-7c09-a4b5-fa788d7a47c3",
    "qty": 5
}
