@product_api_url=product.svc.local
@product_port=8081

### Get products
GET http://{{product_api_url}}:{{product_port}}/products

### Create product
POST http://{{product_api_url}}:{{product_port}}/products
content-type: application/json

{
    "name": "Test product #1",
    "price": 3.99,
    "qty": 10
}

### Get single product (without income)
@product_id=0193ea09-6191-7c09-a4b5-fa788d7a47c3
GET http://{{product_api_url}}:{{product_port}}/products/{{product_id}}

### Change Inventory
PUT http://{{product_api_url}}:{{product_port}}/products/{{product_id}}
content-type: application/json

{
    "qty": 20
}